# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for the Dina platform"
  homepage "https://github.com/dinacomputer/cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.1/dina_0.0.1_darwin_amd64.tar.gz"
      sha256 "6c65a2a0f063fe258d84fddf10e6a7ff655f63da60e01d3f530c284307dd1f39"

      define_method(:install) do
        bin.install "dina"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.1/dina_0.0.1_darwin_arm64.tar.gz"
      sha256 "9e528844d9e4e98b6121239757a53294ed8c6767050205b23cc446de6a0624da"

      define_method(:install) do
        bin.install "dina"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.1/dina_0.0.1_linux_amd64.tar.gz"
      sha256 "a550b3bded53b1db56af62ffa097d9ff32dd7501febc711fe7b8437baf1202a2"
      define_method(:install) do
        bin.install "dina"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.1/dina_0.0.1_linux_arm64.tar.gz"
      sha256 "4ddbf33458edd7217545bbb0278f23526942184e9495114f09ba062255f8ca0b"
      define_method(:install) do
        bin.install "dina"
      end
    end
  end

  test do
    system "#{bin}/dina", "version"
  end
end
