# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dina < Formula
  desc "CLI for the Dina platform"
  homepage "https://github.com/dinacomputer/cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.2/dina_0.0.2_darwin_amd64.tar.gz"
      sha256 "16ec89196eb123cfd0b05475579af111c7cb7ef1f09987fab6b69b900c895b5b"

      define_method(:install) do
        bin.install "dina"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.2/dina_0.0.2_darwin_arm64.tar.gz"
      sha256 "aba2c1e2dae6bc02ce94aed0dc9acba930fd138a87a6447cae4bdbe9dbb86474"

      define_method(:install) do
        bin.install "dina"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.2/dina_0.0.2_linux_amd64.tar.gz"
      sha256 "26d73dd269a4a901c2f4f0030406a0a516aa2119f411bfd77e86359b2fae190e"
      define_method(:install) do
        bin.install "dina"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinacomputer/cli/releases/download/v0.0.2/dina_0.0.2_linux_arm64.tar.gz"
      sha256 "24986c9eab282e66b80c6774d16f51c3728381ceda6cbb522c3697362c6a70c1"
      define_method(:install) do
        bin.install "dina"
      end
    end
  end

  test do
    system "#{bin}/dina", "version"
  end
end
